### ISSUE TITLE
Undefined reference to `showVersion' error when building on Crostini Linux

### ISSUE THREAD

**Issue by pamoroso** [ogdenpm/mklbr#1]
After cloning the mklbr repo on my Crostini Linux system, when I try to build the program I get the error `undefined reference to `showVersion'`:

```
paoloamoroso@penguin:~/cpm/programs/mklbr$ gcc -omklbr -O3 mklbr.c
/usr/bin/ld: /tmp/ccJWLzvS.o: in function `main':
mklbr.c:(.text.startup+0x141): undefined reference to `showVersion'
collect2: error: ld returned 1 exit status
```

I'm using Crostini, the Linux container based on Debian Bullseye of chromeOS, on an ASUS Chromebox 3.

**Comment by ogdenpm** [comment]
Paolo
A documentation error on my behalf.
I recently changed the version model to align with my current approach, but failed to update the build instructions for Linux.
You need to also compile the _version.c file.
I will update the documentation file next week.
Mark

Regards
Mark
________________________________
From: Paolo Amoroso ***@***.***>
Sent: Saturday, November 18, 2023 7:58:53 PM
To: ogdenpm/mklbr ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ogdenpm/mklbr] Undefined reference to `showVersion' error when building on Crostini Linux (Issue #1)


After cloning the mklbr repo on my Crostini Linux system, when I try to build the program I get the error undefined reference to showVersion'`:

***@***.***:~/cpm/programs/mklbr$ gcc -omklbr -O3 mklbr.c
/usr/bin/ld: /tmp/ccJWLzvS.o: in function `main':
mklbr.c:(.text.startup+0x141): undefined reference to `showVersion'
collect2: error: ld returned 1 exit status


I'm using Crostini, the Linux container based on Debian Bullseye of chromeOS, on an ASUS Chromebox 3.

**Comment by pamoroso** [comment]
Thanks, `gcc -omklbr -O3 mklbr.c _version.c` works fine.
